class AppointmentsMapper < Pipeline::TransformMapper
  define_mappings({
    'AppointmentID' => { :to => :id},
    'ContactID' => { :to => :contact_id},
    'CB Date' => { :to => :cb_date},
    'CB Time' => { :to => :cb_time},
    'CB Sale Probability' => { :to => :cb_sale_probability},
    'Comments' => { :to => :comments},
    'ApptStatus' => { :to => :appt_status},
    'Entered' => { :to => :entered},
    'Closes Attempted' => { :to => :closes_attempted},
    'Call First' => { :to => :call_first},
    'RepID' => { :to => :rep_id},
    'Teleconference' => { :to => :teleconference},
    'Pre-Appointment' => { :to => :pre_appointment},
    'e-mailsent' => { :to => :e_mailsent},
    'Lettersent' => { :to => :lettersent},
    'Cooperative' => { :to => :cooperative},
    'References Requested' => { :to => :references_requested},
    'Maintain Contact' => { :to => :maintain_contact},
    'Online Meeting' => { :to => :online_meeting},
    'TimeStart' => { :to => :time_start},
    'TimeEnd' => { :to => :time_end},
    'NoSaleReason' => { :to => :no_sale_reason},
    'Problem1' => { :to => :problem1},
    'Impact1' => { :to => :impact1},
    'Problem2' => { :to => :problem2},
    'Impact2' => { :to => :impact2},
    'Problem3' => { :to => :problem3},
    'Impact3' => { :to => :impact3},
    'Probable ACS Date' => { :to => :probable_acs_date},
    'Probable Sale Date' => { :to => :probable_sale_date},
  })
end