class ContactsMapper < Pipeline::TransformMapper
  define_mappings({
    'ContactID' => { :to => :id},
    'LeadID' => { :to => :lead_id},
    'BCID' => { :to => :bcid},
    'Memo' => { :to => :memo},
    'Date' => { :to => :date},
    'Set Date' => { :to => :set_date},
    'Set Time' => { :to => :set_time},
    'Status' => { :to => :status},
    'Recontact Date' => { :to => :recontact_date},
    'Recontact Time' => { :to => :recontact_time},
    'ApptDate' => { :to => :appt_date},
    'ApptTime' => { :to => :appt_time},
    'Confirmed' => { :to => :confirmed},
    'Faxed' => { :to => :faxed},
    'One-Legged' => { :to => :one_legged},
    'Rcvd' => { :to => :rcvd},
    'Hot Buttons' => { :to => :hot_buttons},
    'Prospect Problems' => { :to => :prospect_problems},
    'Discuss Competition' => { :to => :discuss_competition},
    'History & Success' => { :to => :history_&_success},
    'Knows BMC' => { :to => :knows_bmc},
    'Bad Experience' => { :to => :bad_experience},
    'Prior Consultant' => { :to => :prior_consultant},
    'Presentation Scheduled' => { :to => :presentation_scheduled},
    'Presentation Scheduled Set With' => { :to => :presentation_scheduled_set_with},
    'Presentation Viewed' => { :to => :presentation_viewed},
    'Presentation Score' => { :to => :presentation_score},
    'Expert Date' => { :to => :expert_date},
    'Expert Time' => { :to => :expert_time},
    'Expert Set With' => { :to => :expert_set_with},
    'Expert Topic' => { :to => :expert_topic},
    'Expert Timeframe' => { :to => :expert_timeframe},
    'Expert Time Confirmation' => { :to => :expert_time_confirmation},
  })
end