class EmployeesMapper < Pipeline::TransformMapper
  define_mappings({
    'EmployeeID' => { :to => :id},
    'LastName' => { :to => :last_name},
    'FirstName' => { :to => :first_name},
    'MiddleInitial' => { :to => :middle_initial},
    'PreferredName' => { :to => :preferred_name},
    'SocialSecurityNumber' => { :to => :social_security_number},
    'DepartmentName' => { :to => :department_name},
    'Sex' => { :to => :sex},
    'Title' => { :to => :title},
    'EmailName' => { :to => :email_name},
    'Address' => { :to => :address},
    'City' => { :to => :city},
    'StateOrProvince' => { :to => :state_or_province},
    'PostalCode' => { :to => :postal_code},
    'Country' => { :to => :country},
    'Phone' => { :to => :phone},
    'Fax' => { :to => :fax},
    'Cellular' => { :to => :cellular},
    'Expert Scheduler Phone' => { :to => :expert_scheduler_phone},
    'Birthdate' => { :to => :birthdate},
    'StatusChangeDate' => { :to => :status_change_date},
    'DateHired' => { :to => :date_hired},
    'W-2' => { :to => :w_2},
    'Married' => { :to => :married},
    'SpouseName' => { :to => :spouse_name},
    'Exemptions' => { :to => :exemptions},
    'EmrgcyContactName' => { :to => :emrgcy_contact_name},
    'EmrgcyContactPhone' => { :to => :emrgcy_contact_phone},
    'Active' => { :to => :active},
    'Termination' => { :to => :termination},
    'ReportsTo' => { :to => :reports_to},
    'TrainerID' => { :to => :trainer_id},
    'Business Name' => { :to => :business_name},
    'Fed Tax ID' => { :to => :fed_tax_id},
    'Business Card Name' => { :to => :business_card_name},
    'Emp Ap' => { :to => :emp_ap},
    'I-9 Form' => { :to => :i_9_form},
    'I-9 IDs' => { :to => :i_9_i_ds},
    'Liability Insurance' => { :to => :liability_insurance},
    'W-4 Form' => { :to => :w_4_form},
    'Policy Signoff' => { :to => :policy_signoff},
    'EWA' => { :to => :ewa},
    'Business Proof' => { :to => :business_proof},
    'Resignation' => { :to => :resignation},
    'Notes' => { :to => :notes},
    'Extension' => { :to => :extension},
    'Shift' => { :to => :shift},
    'Program' => { :to => :program},
    'Username' => { :to => :username},
    'Password' => { :to => :password},
  })
end