class LeadsMapper < DataImport::TransformMapper
  define_mappings({
    "LeadID" => { :to => :id },
    "Name" => { :to => :name },
    "Lastname" => { :to => :last_name },
    "Firstname" => { :to => :first_name },
    "Salutation" => { :to => :salutation },
    "Title" => { :to => :title },
    "Gender" => { :to => :gender },
    "Company" => { :to => :company },
    "Year Established" => { :to => :year_established },
    "Address" => { :to => :address },
    "City" => { :to => :city },
    "State" => { :to => :state },
    "County" => { :to => :county },
    "Zip" => { :to => :zip },
    "Phone" => { :to => :phone },
    "Extension" => { :to => :extension },
    "Fax" => { :to => :fax },
    "Cell Phone" => { :to => :cell_phone },
    "Employee Actual" => { :to => :employee_actual },
    "Employee Code" => { :to => :employee_code },
    "Sales Actual" => { :to => :sales_actual },
    "Sales Code" => { :to => :sales_code },
    "SIC Code" => { :to => :sic_code_1 },
    "SIC Description" => { :to => :sic_description_1 },
    "SIC_02" => { :to => :sic_code_2 },
    "DESCRIPTION_02" => { :to => :sic_description_2 },
    "SIC_03" => { :to => :sic_code_3 },
    "DESCRIPTION_03" => { :to => :sic_description_3 },
    "SIC_04" => { :to => :sic_code_4 },
    "DESCRIPTION_04" => { :to => :sic_description_4 },
    "SIC_05" => { :to => :sic_code_5 },
    "DESCRIPTION_05" => { :to => :sic_description_5 },
    "MSA" => { :to => :msa },
    "WEB" => { :to => :web },
    "e-mail" => { :to => :email },
    "Number of PCs" => { :to => :number_of_pcs },
    "Square Footage" => { :to => :square_footage },
    "Own or Lease" => { :to => :own_property, :transform => lambda{ |val| val.downcase == "own" } },
    "Credit Rating" => { :to => :credit_rating },
    "Credit Numeric Score" => { :to => :credit_score },
    "Source" => { :to => :source },
    "Imported" => { :to => :imported_at },
    "Updated" => { :to => :updated_at },
    "Time Zone" => { :to => :timezone }
  })
end