module ApplicantsHelper
  def yes_no_radio(form_object, method)
    "#{form_object.radio_button(method, :true)}&nbsp;Yes&nbsp;#{form_object.radio_button(method, :false)}&nbsp;No"
  end
  
  def grouped_state_provinces_collection
    [
      [
        'United States', [
          [ "Alabama", "AL" ], 
          [ "Alaska", "AK" ], 
          [ "Arizona", "AZ" ], 
          [ "Arkansas", "AR" ], 
          [ "California", "CA" ], 
          [ "Colorado", "CO" ], 
          [ "Connecticut", "CT" ], 
          [ "Delaware", "DE" ], 
          [ "District Of Columbia", "DC" ], 
          [ "Florida", "FL" ], 
          [ "Georgia", "GA" ], 
          [ "Hawaii", "HI" ], 
          [ "Idaho", "ID" ], 
          [ "Illinois", "IL" ], 
          [ "Indiana", "IN" ], 
          [ "Iowa", "IA" ], 
          [ "Kansas", "KS" ], 
          [ "Kentucky", "KY" ], 
          [ "Louisiana", "LA" ], 
          [ "Maine", "ME" ], 
          [ "Maryland", "MD" ], 
          [ "Massachusetts", "MA" ], 
          [ "Michigan", "MI" ], 
          [ "Minnesota", "MN" ], 
          [ "Mississippi", "MS" ], 
          [ "Missouri", "MO" ], 
          [ "Montana", "MT" ], 
          [ "Nebraska", "NE" ], 
          [ "Nevada", "NV" ], 
          [ "New Hampshire", "NH" ], 
          [ "New Jersey", "NJ" ], 
          [ "New Mexico", "NM" ], 
          [ "New York", "NY" ], 
          [ "North Carolina", "NC" ], 
          [ "North Dakota", "ND" ], 
          [ "Ohio", "OH" ], 
          [ "Oklahoma", "OK" ], 
          [ "Oregon", "OR" ], 
          [ "Pennsylvania", "PA" ], 
          [ "Rhode Island", "RI" ], 
          [ "South Carolina", "SC" ], 
          [ "South Dakota", "SD" ], 
          [ "Tennessee", "TN" ], 
          [ "Texas", "TX" ], 
          [ "Utah", "UT" ], 
          [ "Vermont", "VT" ], 
          [ "Virginia", "VA" ], 
          [ "Washington", "WA" ], 
          [ "West Virginia", "WV" ], 
          [ "Wisconsin", "WI" ], 
          [ "Wyoming", "WY" ]
        ]
      ],
      [
        'Canada', [
          ['Alberta', 'AB'],
          ['British Columbia', 'BC'],
          ['Manitoba', 'MB'],
          ['New Brunswick', 'NB'],
          ['Newfoundland and Labrador', 'NL'],
          ['Northwest Territories', 'NT'],
          ['Nova Scotio', 'NS'],
          ['Nunavut', 'NU'],
          ['Ontario', 'ON'],
          ['Prince Edward Island', 'PE'],
          ['Quebec', 'QC'],
          ['Saskatchewan', 'SK'],
          ['Yukon', 'YT'],
        ]
      ],
      [
        'Mexico', [
          ['Aguascalientes', 'AG'],
          ['Baja California Norte', 'BC'],
          ['Baja California Sur', 'BS'],
          ['Chihuahua', 'CH'],
          ['Colima', 'CL'],
          ['Campeche', 'CM'],
          ['Coahuila', 'CO'],
          ['Chiapas', 'CS'],
          ['Distrito Federal', 'DF'],
          ['Durango', 'DG'],
          ['Guerrero', 'GR'],
          ['Guanajuato', 'GT'],
          ['Hidalgo', 'HG'],
          ['Jalisco', 'JA'],
          ['Michoacan', 'MI'],
          ['Morelos', 'MO'],
          ['Nayarit', 'NA'],
          ['Nuevo Leon', 'NL'],
          ['Oaxaca', 'OA'],
          ['Puebla', 'PU'],
          ['Quintana Roo', 'QR'],
          ['Queretaro', 'QT'],
          ['Sinaloa', 'SI'],
          ['San Luis Potosi', 'SL'],
          ['Sonora', 'SO'],
          ['Tabasco', 'TB'],
          ['Tlaxcala', 'TL'],
          ['Tamaulipas', 'TM'],
          ['Veracruz', 'VE'],
          ['Yucatan', 'YU'],
          ['Zacatecas', 'ZA'],
        ]
      ]
    ]
  end
  
end
