class CreateApplicants < ActiveRecord::Migration
  def self.up
    create_table :applicants do |t|
      t.string :applicant_first_name
			t.string :applicant_mi
			t.string :applicant_last_name
			t.string :applicant_preferred_name
			t.string :position_applying_for
			t.string :radio_button_list
			t.string :address
			t.string :city
			t.string :state
			t.string :zip_postal_code
			t.string :country
			t.string :email
			t.string :home_phone
			t.string :cell_num
			t.string :applied_trigon_before
			t.string :currently_employed
			t.string :employer_contact_permission
			t.string :es_business_phone
			t.string :ref_personal_yrs1
			t.string :highest_education_achieved
			t.string :position_experience
			t.string :how_heardof_trigon
			t.string :overall_experience
			t.string :availability
			t.string :ref_professional_name1
			t.string :ref_professional_position1
			t.string :ref_professional_relation1
			t.string :ref_professional_phone_num1
			t.string :ref_professional_relation2
			t.string :ref_professional_position2
			t.string :ref_professional_phone_num2
			t.string :ref_professional_name2
			t.string :ref_personal_name1
			t.string :ref_personal_phone_num1
			t.string :ref_personal_phone_num2
			t.string :ref_personal_name2
			t.string :ref_personal_phone_num3
			t.string :ref_personal_name3
			t.string :ref_personal_relation1
			t.string :ref_personal_yrs2
			t.string :ref_personal_relation2
			t.string :ref_personal_relation3
			t.string :ref_personal_yrs3
			t.string :ref_professional_relation3
			t.string :ref_professional_position3
			t.string :ref_professional_phone_num3
			t.string :ref_professional_name3
			t.string :drop_down_list2
			t.string :skill_web
			t.string :skill_word
			t.string :skill_outlook
			t.string :skill_excel
			t.string :skill_access
			t.string :work_restrictions
			t.string :hs_internet_connection
			t.string :skill_power_point
			t.string :ed_hist_to2
			t.string :ed_hist_to3
			t.string :ed_hist_school3
			t.string :ed_hist_school2
			t.string :ed_hist_graduated2
			t.string :ed_hist_graduated3
			t.string :ed_hist_major3
			t.string :ed_hist_degree3
			t.string :ed_hist_degree2
			t.string :ed_hist_major2
			t.string :ed_hist_major1
			t.string :ed_hist_degree1
			t.string :ed_hist_graduated1
			t.string :ed_hist_school1
			t.string :ed_hist_to1
			t.string :ed_hist_from1
			t.string :ed_hist_from2
			t.string :ed_hist_from3
			t.string :ed_hist_major4
			t.string :ed_hist_degree4
			t.string :ed_hist_graduated4
			t.string :ed_hist_school4
			t.string :ed_hist_to4
			t.string :ed_hist_from4
			t.string :emp_hist_employer1
			t.string :emp_hist_from1
			t.string :emp_hist_to1
			t.string :emp_hist_position1
			t.string :emp_hist_income1
			t.string :emp_hist_reason1
			t.string :emp_hist_reason2
			t.string :emp_hist_income2
			t.string :emp_hist_position2
			t.string :emp_hist_employer2
			t.string :emp_hist_to2
			t.string :emp_hist_from2
			t.string :emp_hist_reason3
			t.string :emp_hist_income3
			t.string :emp_hist_position3
			t.string :emp_hist_employer3
			t.string :emp_hist_to3
			t.string :emp_hist_from3
			t.string :emp_hist_reason4
			t.string :emp_hist_income4
			t.string :emp_hist_position4
			t.string :emp_hist_employer4
			t.string :emp_hist_to4
			t.string :emp_hist_from4
			t.string :text_field3
			t.timestamps
    end
    execute 'CREATE VIEW Applicants ( ApplicantFirstName,ApplicantMI,ApplicantLastName,ApplicantPreferredName,PositionApplyingFor,RadioButtonList,Address,City,State,ZipPostalCode,Country,email,HomePhone,CellNum,AppliedTrigonBefore,CurrentlyEmployed,EmployerContactPermission,ESBusinessPhone,RefPersonalYrs1,HighestEducationAchieved,PositionExperience,HowHeardofTrigon,OverallExperience,Availability,RefProfessionalName1,RefProfessionalPosition1,RefProfessionalRelation1,RefProfessionalPhoneNum1,RefProfessionalRelation2,RefProfessionalPosition2,RefProfessionalPhoneNum2,RefProfessionalName2,RefPersonalName1,RefPersonalPhoneNum1,RefPersonalPhoneNum2,RefPersonalName2,RefPersonalPhoneNum3,RefPersonalName3,RefPersonalRelation1,RefPersonalYrs2,RefPersonalRelation2,RefPersonalRelation3,RefPersonalYrs3,RefProfessionalRelation3,RefProfessionalPosition3,RefProfessionalPhoneNum3,RefProfessionalName3,DropDownList2,Skill-Web,Skill-Word,Skill-Outlook,Skill-Excel,Skill-Access,WorkRestrictions,HSInternetConnection,Skill-PowerPoint,EdHistTo2,EdHistTo3,EdHistSchool3,EdHistSchool2,EdHistGraduated2,EdHistGraduated3,EdHistMajor3,EdHistDegree3,EdHistDegree2,EdHistMajor2,EdHistMajor1,EdHistDegree1,EdHistGraduated1,EdHistSchool1,EdHistTo1,EdHistFrom1,EdHistFrom2,EdHistFrom3,EdHistMajor4,EdHistDegree4,EdHistGraduated4,EdHistSchool4,EdHistTo4,EdHistFrom4,EmpHistEmployer1,EmpHistFrom1,EmpHistTo1,EmpHistPosition1,EmpHistIncome1,EmpHistReason1,EmpHistReason2,EmpHistIncome2,EmpHistPosition2,EmpHistEmployer2,EmpHistTo2,EmpHistFrom2,EmpHistReason3,EmpHistIncome3,EmpHistPosition3,EmpHistEmployer3,EmpHistTo3,EmpHistFrom3,EmpHistReason4,EmpHistIncome4,EmpHistPosition4,EmpHistEmployer4,EmpHistTo4,EmpHistFrom4,TextField3) AS SELECT applicant_first_name,applicant_mi,applicant_last_name,applicant_preferred_name,position_applying_for,radio_button_list,address,city,state,zip_postal_code,country,email,home_phone,cell_num,applied_trigon_before,currently_employed,employer_contact_permission,es_business_phone,ref_personal_yrs1,highest_education_achieved,position_experience,how_heardof_trigon,overall_experience,availability,ref_professional_name1,ref_professional_position1,ref_professional_relation1,ref_professional_phone_num1,ref_professional_relation2,ref_professional_position2,ref_professional_phone_num2,ref_professional_name2,ref_personal_name1,ref_personal_phone_num1,ref_personal_phone_num2,ref_personal_name2,ref_personal_phone_num3,ref_personal_name3,ref_personal_relation1,ref_personal_yrs2,ref_personal_relation2,ref_personal_relation3,ref_personal_yrs3,ref_professional_relation3,ref_professional_position3,ref_professional_phone_num3,ref_professional_name3,drop_down_list2,skill_web,skill_word,skill_outlook,skill_excel,skill_access,work_restrictions,hs_internet_connection,skill_power_point,ed_hist_to2,ed_hist_to3,ed_hist_school3,ed_hist_school2,ed_hist_graduated2,ed_hist_graduated3,ed_hist_major3,ed_hist_degree3,ed_hist_degree2,ed_hist_major2,ed_hist_major1,ed_hist_degree1,ed_hist_graduated1,ed_hist_school1,ed_hist_to1,ed_hist_from1,ed_hist_from2,ed_hist_from3,ed_hist_major4,ed_hist_degree4,ed_hist_graduated4,ed_hist_school4,ed_hist_to4,ed_hist_from4,emp_hist_employer1,emp_hist_from1,emp_hist_to1,emp_hist_position1,emp_hist_income1,emp_hist_reason1,emp_hist_reason2,emp_hist_income2,emp_hist_position2,emp_hist_employer2,emp_hist_to2,emp_hist_from2,emp_hist_reason3,emp_hist_income3,emp_hist_position3,emp_hist_employer3,emp_hist_to3,emp_hist_from3,emp_hist_reason4,emp_hist_income4,emp_hist_position4,emp_hist_employer4,emp_hist_to4,emp_hist_from4,text_field3 FROM applicants'
  end

  def self.down
    execute 'DROP VIEW Applicants'
    drop_table :applicants
  end
end
