class CreateQuick Analyses < ActiveRecord::Migration
  def self.up
    create_table :quick_analyses do |t|
      t.integer :id
			t.string :phone
			t.string :general_1_p
			t.string :general_1_a
			t.string :general_1_w
			t.string :general_2_p
			t.string :general_2_a
			t.string :general_2_w
			t.string :general_3_p
			t.string :general_3_a
			t.string :general_3_w
			t.string :general_4_p
			t.string :general_4_a
			t.string :general_4_w
			t.string :industrial_1_p
			t.string :industrial_1_a
			t.string :industrial_1_w
			t.string :industrial_2_p
			t.string :industrial_2_a
			t.string :industrial_2_w
			t.string :industrial_3_p
			t.string :industrial_3_a
			t.string :industrial_3_w
			t.string :industrial_4_p
			t.string :industrial_4_a
			t.string :industrial_4_w
			t.string :industrial_5_p
			t.string :industrial_5_a
			t.string :industrial_5_w
			t.string :industrial_6_p
			t.string :industrial_6_a
			t.string :industrial_6_w
			t.string :finance_1_p
			t.string :finance_1_a
			t.string :finance_1_w
			t.string :finance_2_p
			t.string :finance_2_a
			t.string :finance_2_w
			t.string :budget_1_p
			t.string :budget_1_a
			t.string :budget_1_w
			t.string :budget_2_p
			t.string :budget_2_a
			t.string :budget_2_w
			t.string :budget_3_p
			t.string :budget_3_a
			t.string :budget_3_w
			t.string :budget_4_p
			t.string :budget_4_a
			t.string :budget_4_w
			t.string :accounting_1_p
			t.string :accounting_1_a
			t.string :accounting_1_w
			t.string :accounting_2_p
			t.string :accounting_2_a
			t.string :accounting_2_w
			t.string :accounting_3_p
			t.string :accounting_3_a
			t.string :accounting_3_w
			t.string :research_1_p
			t.string :research_1_a
			t.string :research_1_w
			t.string :research_2_p
			t.string :research_2_a
			t.string :research_2_w
			t.string :research_3_p
			t.string :research_3_a
			t.string :research_3_w
			t.string :control_1_p
			t.string :control_1_a
			t.string :control_1_w
			t.string :control_2_p
			t.string :control_2_a
			t.string :control_2_w
			t.string :control_3_p
			t.string :control_3_a
			t.string :control_3_w
			t.string :control_4_p
			t.string :control_4_a
			t.string :control_4_w
			t.string :control_5_p
			t.string :control_5_a
			t.string :control_5_w
			t.string :control_6_p
			t.string :control_6_a
			t.string :control_6_w
			t.string :control_7_p
			t.string :control_7_a
			t.string :control_7_w
			t.string :sales_1_p
			t.string :sales_1_a
			t.string :sales_1_w
			t.string :sales_2_p
			t.string :sales_2_a
			t.string :sales_2_w
			t.string :sales_3_p
			t.string :sales_3_a
			t.string :sales_3_w
			t.string :sales_4_p
			t.string :sales_4_a
			t.string :sales_4_w
			t.string :sales_5_p
			t.string :sales_5_a
			t.string :sales_5_w
			t.string :sales_6_p
			t.string :sales_6_a
			t.string :sales_6_w
			t.string :sales_7_p
			t.string :sales_7_a
			t.string :sales_7_w
			t.string :purchasing_1_p
			t.string :purchasing_1_a
			t.string :purchasing_1_w
			t.string :plant_engineering_1_p
			t.string :plant_engineering_1_a
			t.string :plant_engineering_1_w
			t.string :scheduling_1_p
			t.string :scheduling_1_a
			t.string :scheduling_1_w
			t.string :qc_1_p
			t.string :qc_1_a
			t.string :qc_1_w
			t.string :tool_engineering_1_p
			t.string :tool_engineering_1_a
			t.string :tool_engineering_1_w
			t.string :methods_engineering_1_p
			t.string :methods_engineering_1_a
			t.string :methods_engineering_1_w
			t.string :production_1_p
			t.string :production_1_a
			t.string :production_1_w
			t.string :warehousing_1_p
			t.string :warehousing_1_a
			t.string :warehousing_1_w
			t.string :computerization_1_p
			t.string :computerization_1_a
			t.string :computerization_1_w
			t.string :computerization_2_p
			t.string :computerization_2_a
			t.string :computerization_2_w
			t.string :computerization_3_p
			t.string :computerization_3_a
			t.string :computerization_3_w
			t.string :computerization_4_p
			t.string :computerization_4_a
			t.string :computerization_4_w
			t.string :internet_1_p
			t.string :internet_1_a
			t.string :internet_1_w
			t.string :general_comments
			t.string :employee_comments
			t.string :finance_comments
			t.string :budget_comments
			t.string :accounting_comments
			t.string :cost_comments
			t.string :sales_comments
			t.string :mfg_comments
			t.string :computer_comments
			t.string :imported
			t.timestamps
    end
    execute 'CREATE VIEW Quick Analysis ( ID,Phone,General 1-P,General 1-A,General 1-W,General 2-P,General 2-A,General 2-W,General 3-P,General 3-A,General 3-W,General 4-P,General 4-A,General 4-W,Industrial 1-P,Industrial 1-A,Industrial 1-W,Industrial 2-P,Industrial 2-A,Industrial 2-W,Industrial 3-P,Industrial 3-A,Industrial 3-W,Industrial 4-P,Industrial 4-A,Industrial 4-W,Industrial 5-P,Industrial 5-A,Industrial 5-W,Industrial 6-P,Industrial 6-A,Industrial 6-W,Finance 1-P,Finance 1-A,Finance 1-W,Finance 2-P,Finance 2-A,Finance 2-W,Budget 1-P,Budget 1-A,Budget 1-W,Budget 2-P,Budget 2-A,Budget 2-W,Budget 3-P,Budget 3-A,Budget 3-W,Budget 4-P,Budget 4-A,Budget 4-W,Accounting 1-P,Accounting 1-A,Accounting 1-W,Accounting 2-P,Accounting 2-A,Accounting 2-W,Accounting 3-P,Accounting 3-A,Accounting 3-W,Research 1-P,Research 1-A,Research 1-W,Research 2-P,Research 2-A,Research 2-W,Research 3-P,Research 3-A,Research 3-W,Control 1-P,Control 1-A,Control 1-W,Control 2-P,Control 2-A,Control 2-W,Control 3-P,Control 3-A,Control 3-W,Control 4-P,Control 4-A,Control 4-W,Control 5-P,Control 5-A,Control 5-W,Control 6-P,Control 6-A,Control 6-W,Control 7-P,Control 7-A,Control 7-W,Sales 1-P,Sales 1-A,Sales 1-W,Sales 2-P,Sales 2-A,Sales 2-W,Sales 3-P,Sales 3-A,Sales 3-W,Sales 4-P,Sales 4-A,Sales 4-W,Sales 5-P,Sales 5-A,Sales 5-W,Sales 6-P,Sales 6-A,Sales 6-W,Sales 7-P,Sales 7-A,Sales 7-W,Purchasing 1-P,Purchasing 1-A,Purchasing 1-W,Plant Engineering 1-P,Plant Engineering 1-A,Plant Engineering 1-W,Scheduling 1-P,Scheduling 1-A,Scheduling 1-W,QC 1-P,QC 1-A,QC 1-W,Tool Engineering 1-P,Tool Engineering 1-A,Tool Engineering 1-W,Methods Engineering 1-P,Methods Engineering 1-A,Methods Engineering 1-W,Production 1-P,Production 1-A,Production 1-W,Warehousing 1-P,Warehousing 1-A,Warehousing 1-W,Computerization 1-P,Computerization 1-A,Computerization 1-W,Computerization 2-P,Computerization 2-A,Computerization 2-W,Computerization 3-P,Computerization 3-A,Computerization 3-W,Computerization 4-P,Computerization 4-A,Computerization 4-W,Internet 1-P,Internet 1-A,Internet 1-W,General-Comments,Employee-Comments,Finance-Comments,Budget-Comments,Accounting-Comments,Cost-Comments,Sales-Comments,Mfg-Comments,Computer-Comments,Imported) AS SELECT id,phone,general_1_p,general_1_a,general_1_w,general_2_p,general_2_a,general_2_w,general_3_p,general_3_a,general_3_w,general_4_p,general_4_a,general_4_w,industrial_1_p,industrial_1_a,industrial_1_w,industrial_2_p,industrial_2_a,industrial_2_w,industrial_3_p,industrial_3_a,industrial_3_w,industrial_4_p,industrial_4_a,industrial_4_w,industrial_5_p,industrial_5_a,industrial_5_w,industrial_6_p,industrial_6_a,industrial_6_w,finance_1_p,finance_1_a,finance_1_w,finance_2_p,finance_2_a,finance_2_w,budget_1_p,budget_1_a,budget_1_w,budget_2_p,budget_2_a,budget_2_w,budget_3_p,budget_3_a,budget_3_w,budget_4_p,budget_4_a,budget_4_w,accounting_1_p,accounting_1_a,accounting_1_w,accounting_2_p,accounting_2_a,accounting_2_w,accounting_3_p,accounting_3_a,accounting_3_w,research_1_p,research_1_a,research_1_w,research_2_p,research_2_a,research_2_w,research_3_p,research_3_a,research_3_w,control_1_p,control_1_a,control_1_w,control_2_p,control_2_a,control_2_w,control_3_p,control_3_a,control_3_w,control_4_p,control_4_a,control_4_w,control_5_p,control_5_a,control_5_w,control_6_p,control_6_a,control_6_w,control_7_p,control_7_a,control_7_w,sales_1_p,sales_1_a,sales_1_w,sales_2_p,sales_2_a,sales_2_w,sales_3_p,sales_3_a,sales_3_w,sales_4_p,sales_4_a,sales_4_w,sales_5_p,sales_5_a,sales_5_w,sales_6_p,sales_6_a,sales_6_w,sales_7_p,sales_7_a,sales_7_w,purchasing_1_p,purchasing_1_a,purchasing_1_w,plant_engineering_1_p,plant_engineering_1_a,plant_engineering_1_w,scheduling_1_p,scheduling_1_a,scheduling_1_w,qc_1_p,qc_1_a,qc_1_w,tool_engineering_1_p,tool_engineering_1_a,tool_engineering_1_w,methods_engineering_1_p,methods_engineering_1_a,methods_engineering_1_w,production_1_p,production_1_a,production_1_w,warehousing_1_p,warehousing_1_a,warehousing_1_w,computerization_1_p,computerization_1_a,computerization_1_w,computerization_2_p,computerization_2_a,computerization_2_w,computerization_3_p,computerization_3_a,computerization_3_w,computerization_4_p,computerization_4_a,computerization_4_w,internet_1_p,internet_1_a,internet_1_w,general_comments,employee_comments,finance_comments,budget_comments,accounting_comments,cost_comments,sales_comments,mfg_comments,computer_comments,imported FROM quick_analyses'
  end

  def self.down
    execute 'DROP VIEW Quick Analysis'
    drop_table :quick_analyses
  end
end
