class QuestionsByLeadIdsMapper < Pipeline::TransformMapper
  define_mappings({
    'LeadID' => { :to => :lead_id},
    'SIC Division' => { :to => :sic_division},
    'SIC Code' => { :to => :sic_code},
    'Q01' => { :to => :q01},
    'Q02' => { :to => :q02},
    'Q03' => { :to => :q03},
    'Q04' => { :to => :q04},
    'Q05' => { :to => :q05},
    'Q06' => { :to => :q06},
    'Q07' => { :to => :q07},
    'Q08' => { :to => :q08},
    'Q09' => { :to => :q09},
    'Q10' => { :to => :q10},
    'Q11' => { :to => :q11},
    'Q12' => { :to => :q12},
    'Q13' => { :to => :q13},
    'Q14' => { :to => :q14},
    'Q15' => { :to => :q15},
    'Q16' => { :to => :q16},
    'Q17' => { :to => :q17},
    'Q18' => { :to => :q18},
    'Q19' => { :to => :q19},
    'Q20' => { :to => :q20},
    'Q21' => { :to => :q21},
    'Q22' => { :to => :q22},
    'Q23' => { :to => :q23},
    'Q24' => { :to => :q24},
    'Q25' => { :to => :q25},
    'Q26' => { :to => :q26},
    'Q27' => { :to => :q27},
    'Q28' => { :to => :q28},
    'Q29' => { :to => :q29},
    'Q30' => { :to => :q30},
    'Q31' => { :to => :q31},
    'Q32' => { :to => :q32},
    'Q33' => { :to => :q33},
    'Q34' => { :to => :q34},
    'Q35' => { :to => :q35},
    'Q36' => { :to => :q36},
    'Question 1' => { :to => :question_1},
    'Question 2' => { :to => :question_2},
    'Question 3' => { :to => :question_3},
    'Question 4' => { :to => :question_4},
    'Question 5' => { :to => :question_5},
    'Question 6' => { :to => :question_6},
    'Question 7' => { :to => :question_7},
    'Question 8' => { :to => :question_8},
    'Question 9' => { :to => :question_9},
    'Question 10' => { :to => :question_10},
    'Question 11' => { :to => :question_11},
    'Question 12' => { :to => :question_12},
    'Question 13' => { :to => :question_13},
    'Question 14' => { :to => :question_14},
    'Question 15' => { :to => :question_15},
    'Question 16' => { :to => :question_16},
    'Question 17' => { :to => :question_17},
    'Question 18' => { :to => :question_18},
    'Question 19' => { :to => :question_19},
    'Question 20' => { :to => :question_20},
    'Question 21' => { :to => :question_21},
    'Question 22' => { :to => :question_22},
    'Question 23' => { :to => :question_23},
    'Question 24' => { :to => :question_24},
    'Question 25' => { :to => :question_25},
    'Question 26' => { :to => :question_26},
    'Question 27' => { :to => :question_27},
    'Question 28' => { :to => :question_28},
    'Question 29' => { :to => :question_29},
    'Question 30' => { :to => :question_30},
    'Question 31' => { :to => :question_31},
    'Question 32' => { :to => :question_32},
    'Question 33' => { :to => :question_33},
    'Question 34' => { :to => :question_34},
    'Question 35' => { :to => :question_35},
    'Question 36' => { :to => :question_36},
    'Question 99' => { :to => :question_99},
    'Question 100' => { :to => :question_100},
  })
end